### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by hht980309** [xihuiwu/ProbabilisticRRT#1]
Hello! I am doing my undergraduate degree, about cooperative control of unsignalized intersections.
1.I want to  ask if this project is used for cooperative control of vehicles at unsignalized intersections? 
2.If I want to run, what requirements do I need?

**Comment by xihuiwu** [comment]
1. Hello, this planning algorithm is dedicated to planning a high-level trajectory for a single autonomous vehicle. If you are looking into cooperative control under unsignalized intersections, you could look at this survey paper which summarizes some cooperative control methods. 

"Cooperative Intersection Management: A Survey"

2. If you want to run the algorithm, you need to write a class that is used for iteratively generating a tree through the provided codes. Required packages should be numpy, scipy, matplotlib, and treelib.

**Comment by hht980309** [comment]
Ok，Thank you！
